### ISSUE TITLE
Build Puer-js for Browser 导出js的js路径问题

### ISSUE THREAD

**Issue by mi1890** [zombieyang/puerts-unity-webgl#2]
目前的处理策略,需要把js放到resource目录下
否则生成的puerts_browser_js_resources.js中的js路径都是都有盘符的全路径
excutemodule会有问题

glob-js/index.js

line:87
function getAllJSFile (fileGlobbers) {
    const allJSFile = fileGlobbers
        .reduce((retArr, globber)=> {
            return retArr.concat(
                glob.sync(path.normalize(globber))
            )
        }, [])
        .filter(jsfile => {
            return jsfile.indexOf('Editor') == -1 && jsfile.indexOf('node_modules') == -1
        })
        .map(jsfile => {
            let resourceNameMatcher = jsfile.split('Resources/');
            let resourceName = resourceNameMatcher[resourceNameMatcher.length - 1];
            resourceName = resourceName.replace(/\.txt$/, '');

            return {
                resourceName,
                jsfile
            }
        })

    return allJSFile;
}

**Comment by zombieyang** [comment]
你搞错了，是这个项目

https://github.com/zombieyang/puerts_unity_webgl_demo
